---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    ansible_python_interpreter: /usr/bin/python3
    username: newuser
    softwares:
      - apache2
      - python-dev
    users:
      ged:
        name: Hawk
      arpha:
        name: Tenar
  vars_files:
    - ./confidential-vars.yml
  tasks:
    - name: Add new user
      user:
        name: "{{ username }}"
        group: admin
        shell: /bin/bash
    - name: Send slack messege
      slack:
        token: "{{ sandbox.slack.token }}"
        msg: 'Hello, ansible!!'
      become: no
      vars:
        ansible_python_interpreter: /Users/koji-sudo/.pyenv/shims/python
      delegate_to: localhost
    - name: Test debug message
      debug: msg="Hello, debug module. It can show variables. username={{ username }}"
    - name: /opt/foo以下にbin, conf, logディレクトリ作成
      file: path=/opt/foo/{{ item }} state=directory
      with_items:
        - bin
        - conf
        - log
    - name: aptでインストール
      apt:
        name: "{{ softwares }}"
        update_cache: yes
    - name: Print phone records
      user: name={{ item.key }} comment={{ item.value.name }}
      with_dict: "{{ users }}"
    - name: 日付を得る
      command: date "+%Y%m%d"
      register: date
    - debug: var=date
    - name: 日付のファイルを作成する
      file: path=/tmp/log.{{ date.stdout }} state=touch
    - name: 日付が9/24だったら
      command: echo "今日は9/24です"
      when: date.stdout == "20180924"
    - name: 日付が9/24ではなかったら
      command: echo "今日は9/24ではありません"
      when: date.stdout != "20180924"
