---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    ansible_python_interpreter: /usr/bin/python3
    username: newuser
  tasks:
    - name: Add new user
      user: name={{ username }} group=admin shell=/bin/bash
